version: "3"

services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_USER=${ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
      - GF_USERS_ALLOW_SIGN_UP=false
    restart: unless-stopped
    ports:
      - 3000:3000

  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    environment: 
      - DOCKER_INFLUXDB_INIT_USERNAME=${ADMIN_USER:-admin}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${ADMIN_USER:-admin}
      - DOCKER_INFLUXDB_INIT_ORG=savantly
      - DOCKER_INFLUXDB_INIT_BUCKET=test
    ports:
      - 8086:8086